### ISSUE TITLE
write a code as specified in the youtube channel

### ISSUE THREAD

**Issue by ShubhamNagure** [ShubhamNagure/vsfs#1]

**Comment by jaybhavsar555** [comment]
Progress- Create a file in FS and sync_fs
pending mount that file.

**Comment by jaybhavsar555** [comment]
Done with the print the content of the FS

**Comment by jaybhavsar555** [comment]
Currently working on the File Allocation:

**Comment by jaybhavsar555** [comment]
Simply Allocate the File to the Fs.

**Comment by jaybhavsar555** [comment]
Currently Working on:
to Write some data to the file or disk block.

**Comment by jaybhavsar555** [comment]
Done with Writing Byte data into the file in the Fs.

**Comment by jaybhavsar555** [comment]
Done with Video :)
